ALTER TABLE deals ADD COLUMN IF NOT EXISTS max_user_id VARCHAR(64);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS max_goal_sent BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS max_goal_response TEXT;