ALTER TABLE lead_clicks ADD COLUMN IF NOT EXISTS deal_id BIGINT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS order_pending BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS order_sent BOOLEAN NOT NULL DEFAULT FALSE;